package com.emamagic.spring_security;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * 1. request to localhost:8080/hello, redirect us to localhost:8080/login by Spring Security
 * 2. we should login first by defaults params -> username: user and password: [generated by Spring security in Run]
 * 3. also we could logout by calling localhost:8080/logout
 * 4. by default Spring Security does Basic Authentication -> header [Authorization  Basic base64(username:password)]
 * 5. we can modify the username and password by overriding it into  application.yaml or ... (next branches)
 * */
@SpringBootApplication
public class SpringSecurityApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringSecurityApplication.class, args);
	}

}
